### PR TITLE
added some more parameters for metadata transformation

### PR DESCRIPTION
**Pull request by dweidenfeld**
added
- Last-Modified
- Display-Url
- Crawl-Once
- Lock

as parameters to be passed through to the metadata/document transformer, so that you can modify metadata based on more information

### CODE REVIEW

**Comment by dweidenfeld** [comment]
(1) is fixed

(2) is fixed with as good as I could do it. Is there some rule how to group your imports?
I installed the google-code-style.xml in my IntelliJ, so I thought that this should work for you ;)

**Comment by BrettMichaelJohnson** [comment]
On Jul 16, 2015, at 12:50 AM, Dominik Weidenfeld notifications@github.com wrote:

> (1) is fixed
> 
> (2) is fixed with as good as I could do it. Is there some rule how to group your imports?

The rules for grouping and sorting imports are outlined
in the Google Java style guide: 
https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s3.3-import-statements

The import statements were in the correct order and
spacing in the original file, and you neither added nor

removed any.  So simply restoring the imports to their
original arrangement should suffice.

Your pull request also contains numerous changes in 
whitespace with no other functional code changes.
Some were changes in indentation, but most were
deleting trailing whitespace on lines.
This is discouraged for several reasons.  It makes
it difficult for us as reviewers to focus on your 
actual functional changes.  It also pollutes the 
version control history for those lines.

When problems are found with a particular piece of
code, we often use git blame to determine the author
and commit revision where that code was introduced
or modified.  We then examine all the changes for that
particular commit, the log entry, and the code review,
to try to understand why the code was written as it
was.  Gratuitous changes alter that history.

Since more than half of the changes in the code
are non-functional changes (re-ordering the imports
and changing whitespace), you may find it more
convenient to use git reset to restore the files to their
original state, then re-apply just your changes to 
the transform() method.

—
Brett M. Johnson

**Comment by PapaJoltOmega** [comment]
Thanks Brett for the nice explanation.

I've added a couple of comments to the 2nd commit.

Thank you for this work,
PJ

**Comment by dweidenfeld** [comment]
Thank you for your response. I will change the code style and implement the checks as you wanted (maybe beginning next week).
The code style changes has only been made because the IDE optimises the code on save automatically. I will try to revert my changes completely and only add my changes (maybe with a normal text editor).

**Pull request closed without merging**
